### ISSUE TITLE
properties.schema

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-timedSequence#2]
pretty please? :)

**Comment by hbaileylxd** [comment]
pretty pretty please? :)

**Comment by moloko** [comment]
let me see if I have time tomorrow

~~one thing to bear in mind - although this looks like it's a question component, it doesn't have all the behaviours you'd expect from a question component. I don't think it sets a score, pretty sure it doesn't handle multiple attempts... that sort of thing. You definitely don't want to use it within an assessment as-is.~~

**Comment by moloko** [comment]
@hmaffin all done, give it a try and let me know how you get on

**Comment by hbaileylxd** [comment]
Awww you are such a good guy!

**Comment by samumist** [comment]
@hmaffin 
Have you got it work on AT?

I couldn't. 

The plugin is uploaded successfully and I can set up a component with it. But when it comes to the previewing, it is just a spin loading icon with the following error in console:
`Uncaught Error: timedSequence component not found. Is it installed and included?`

**Comment by oliverfoster** [comment]
The component is registered as `timed-sequence` not `timedSequence`.
https://github.com/cgkineo/adapt-timedSequence/blob/master/js/adapt-timed-sequence.js#L194

Might have something to do with it.

**Comment by samumist** [comment]
Thanks @oliverfoster 
Yes, you're right. Have to change the `component` property in `bower.json` from `timedSequence` to `timed-sequence`, then it works.

the property.schema is missing the `_control` part.

```
    "_controls": {
        "start": "Start",
        "answer": "ID",
        "complete": "Completed!"
},
```

I'll try to send in a PR later.

**Comment by oliverfoster** [comment]
merged and released. can you confirm all is ok?

**Comment by samumist** [comment]
I tested on AT, it works great!

**Comment by oliverfoster** [comment]
thanks dude 👍
